stages:
  - build
  - test
  - deploy

variables:
  NODE_VERSION: "22.14.0"


build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - cd frontend
    - npm ci
    - export OPENAI_API_KEY="${OPENAI_API_KEY}"
    - npm run build
  variables:
    VITE_PUBLIC_OPENAI_API_KEY: ${OPENAI_API_KEY}
    PUBLIC_OPENAI_API_KEY: ${OPENAI_API_KEY}

test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - cd backend
    - ./pocketbaseLinux serve &
    - cd
    - cd frontend
    - npm ci
    - export OPENAI_API_KEY="${OPENAI_API_KEY}"
    - npm test
  variables:
    VITE_PUBLIC_OPENAI_API_KEY: ${OPENAI_API_KEY}
    PUBLIC_OPENAI_API_KEY: ${OPENAI_API_KEY}

deploy:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - cd frontend
    - npm ci
    - export OPENAI_API_KEY="${OPENAI_API_KEY}"
    - npm run build
  variables:
    VITE_PUBLIC_OPENAI_API_KEY: ${OPENAI_API_KEY}
    PUBLIC_OPENAI_API_KEY: ${OPENAI_API_KEY}