name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@v3
    
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
    
    # Install PocketBase
    - name: Install PocketBase
      run: |
        curl -L https://github.com/pocketbase/pocketbase/releases/download/v0.22.0/pocketbase_0.22.0_linux_amd64.zip -o pocketbase.zip
        unzip pocketbase.zip
        chmod +x pocketbase
    
    # Build Tailwind CSS
    - name: Build Tailwind CSS
      run: npx tailwindcss -i ./src/input.css -o ./public/output.css
    
    # Build Svelte app
    - name: Build Svelte
      run: npm run build
    
    # Run tests (assuming you have tests set up)
    - name: Run Tests
      run: npm test
      if: ${{ always() }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
    
    # Build application
    - name: Build Application
      run: |
        npx tailwindcss -i ./src/input.css -o ./public/output.css
        npm run build
    
    # Deploy to server (example using SSH)
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /path/to/deployment
          git pull origin main
          npm ci
          npm run build
          # Restart PocketBase service
          systemctl restart pocketbase

env:
  # Environment variables
  NODE_ENV: production
